import * as stylex from '@stylexjs/stylex'

export const authStyles = stylex.create({
  page: {
    display: 'grid',
    minHeight: '100dvh',
    padding: 24,
    placeItems: 'center',
    backgroundColor: '#f7f4ed',
    backgroundImage: 'radial-gradient(ellipse at 50% 35%, #fffdf7, transparent 75%)',
    color: '#513c49',
    fontFamily: 'Arial, Helvetica, sans-serif',
  },
  card: {
    width: 'min(100%, 460px)',
    padding: '24px 38px 40px',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#ffffff',
    borderRadius: 28,
    backgroundColor: '#fffdf8d9',
    boxShadow: '0 24px 60px -30px #66532e66, inset 0 1px 0 #ffffff',
    textAlign: 'center',
    '@media (max-width: 700px)': { padding: '20px 24px 32px' },
  },
  logo: {
    display: 'block',
    width: 'min(100%, 300px)',
    height: 'auto',
    margin: '0 auto 20px',
  },
  eyebrow: {
    margin: '0 0 14px',
    color: '#9a526f',
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: '0.14em',
    textTransform: 'uppercase',
  },
  title: {
    margin: 0,
    fontSize: 'clamp(20px, 5vw, 30px)',
    lineHeight: 1.5,
    letterSpacing: '0.02em',
  },
  description: {
    margin: '20px 0 28px',
    color: '#786672',
    fontSize: 15,
    lineHeight: 1.8,
  },
  googleButton: {
    display: 'flex',
    width: '100%',
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    padding: '12px 18px',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#e5cbd6',
    borderRadius: 12,
    backgroundColor: { default: '#ffffff', ':hover': '#fff0f6' },
    color: '#513c49',
    fontFamily: 'inherit',
    fontSize: 15,
    fontWeight: 700,
    cursor: { default: 'pointer', ':disabled': 'wait' },
    opacity: { default: 1, ':disabled': 0.65 },
    outline: { default: 'none', ':focus-visible': '2px solid #a34d74' },
    outlineOffset: 3,
  },
  googleMark: {
    display: 'grid',
    width: 23,
    height: 23,
    placeItems: 'center',
    borderRadius: 999,
    backgroundColor: '#ffffff',
    color: '#4285f4',
    fontFamily: 'Arial, Helvetica, sans-serif',
    fontSize: 18,
    fontWeight: 700,
    boxShadow: '0 0 0 1px #e2e2e2',
  },
  status: { color: '#786672', fontSize: 15 },
  error: { margin: '18px 0 0', color: '#aa3045', fontSize: 13, lineHeight: 1.6 },
  account: {
    position: 'fixed',
    top: 14,
    right: 14,
    zIndex: 10000,
    display: 'flex',
    maxWidth: 'calc(100vw - 28px)',
    alignItems: 'center',
    gap: 10,
    padding: '7px 8px 7px 13px',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#ffffffcc',
    borderRadius: 999,
    backgroundColor: '#fffdf8e8',
    boxShadow: '0 8px 24px -14px #5c4a2f66',
    backdropFilter: 'blur(12px)',
  },
  userName: {
    maxWidth: 180,
    overflow: 'hidden',
    color: '#5f5b51',
    fontSize: 12,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    '@media (max-width: 700px)': { maxWidth: 110 },
  },
  signOutButton: {
    padding: '7px 11px',
    borderWidth: 0,
    borderRadius: 999,
    backgroundColor: { default: '#ebe6db', ':hover': '#dfd8ca' },
    color: '#57534a',
    fontFamily: 'inherit',
    fontSize: 11,
    fontWeight: 700,
    cursor: { default: 'pointer', ':disabled': 'wait' },
    outline: { default: 'none', ':focus-visible': '2px solid #676d54' },
  },
  accountError: {
    position: 'absolute',
    top: 'calc(100% + 8px)',
    right: 0,
    width: 240,
    padding: 10,
    borderRadius: 8,
    backgroundColor: '#fff0f2',
    color: '#aa3045',
    fontSize: 12,
    boxShadow: '0 8px 20px -12px #7c2736aa',
  },
})
