import * as stylex from '@stylexjs/stylex'

export const paperStyles = stylex.create({
  yellow: {
    backgroundColor: '#fff39b',
    backgroundImage: 'linear-gradient(135deg, #fff7af, #fff18c)',
  },
  pink: {
    backgroundColor: '#f8bbd6',
    backgroundImage: 'linear-gradient(135deg, #fbd0e4, #f7b4d2)',
  },
  blue: {
    backgroundColor: '#b9e3f7',
    backgroundImage: 'linear-gradient(135deg, #c9ebfb, #addcf3)',
  },
  green: {
    backgroundColor: '#c8efbc',
    backgroundImage: 'linear-gradient(135deg, #d7f6cd, #bcebae)',
  },
  purple: {
    backgroundColor: '#dbc4f4',
    backgroundImage: 'linear-gradient(135deg, #e5d4f8, #d1b5ef)',
  },
  orange: {
    backgroundColor: '#ffd08f',
    backgroundImage: 'linear-gradient(135deg, #ffdcab, #ffc477)',
  },
})

export const styles = stylex.create({
  app: {
    backgroundColor: '#f7f4ed',
    color: '#393a32',
    fontFamily: 'Arial, Helvetica, sans-serif',
  },
  board: {
    position: 'relative',
    width: '100%',
    height: '100dvh',
    overflow: 'hidden',
    isolation: 'isolate',
    margin: 0,
    backgroundImage: 'radial-gradient(ellipse at 50% 35%, #fffdf780, transparent 75%)',
  },
  count: {
    margin: '0 0 12px',
    textAlign: 'center',
    fontSize: 11,
    color: '#8a877b',
    letterSpacing: '0.04em',
  },
  layer: (zIndex: number) => ({ zIndex }),
  note: {
    position: 'absolute',
    width: 206,
    height: 206,
    borderRadius: '2px 3px 19px 3px',
    boxShadow: '2px 9px 11px -5px #66532e30, 0 18px 24px -17px #66532e38',
    transformOrigin: '50% 25%',
  },
  position: (x: number, y: number, angle: number, zIndex: number) => ({
    left: x,
    top: y,
    transform: `rotate(${angle}deg)`,
    zIndex,
  }),
  lifted: { boxShadow: '4px 20px 28px -10px #66532e50', cursor: 'grabbing' },
  handle: {
    display: 'flex',
    width: '100%',
    height: 28,
    padding: 0,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 0,
    borderRadius: '2px 3px 0 0',
    backgroundColor: { default: '#ffffff14', ':hover': '#ffffff35' },
    cursor: { default: 'grab', ':active': 'grabbing' },
    touchAction: 'none',
    outline: { default: 'none', ':focus-visible': '2px solid #676d54' },
    outlineOffset: 3,
  },
  grip: {
    display: 'block',
    width: 21,
    height: 3,
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: '#71634628',
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: '#71634628',
  },
  editor: {
    display: 'block',
    width: '100%',
    height: 173,
    padding: '7px 23px 12px',
    borderWidth: 0,
    resize: 'none',
    outline: { default: 'none', ':focus-visible': '1px dashed #71634660' },
    outlineOffset: -8,
    backgroundColor: 'transparent',
    color: '#38362c',
    fontFamily: 'inherit',
    fontSize: 18,
    lineHeight: 1.65,
    letterSpacing: '0.025em',
    scrollbarWidth: 'thin',
  },
  fold: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    width: 20,
    height: 20,
    borderRadius: '16px 0 17px 0',
    backgroundImage:
      'linear-gradient(135deg, #ffffff00 20%, #ffffff65 48%, #0000000c 52%, #ffffff40 100%)',
    boxShadow: '-2px -2px 3px #675d2710',
    pointerEvents: 'none',
  },
  preview: { pointerEvents: 'none' },
  dock: {
    position: 'absolute',
    bottom: 15,
    left: '50%',
    transform: 'translateX(-50%)',
    width: 694,
  },
  tray: {
    display: 'flex',
    gap: 14,
    padding: '15px 21px 0',
    height: 108,
    overflow: 'hidden',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#ffffffdd',
    borderBottomColor: '#e7e0d2',
    borderRadius: '17px 17px 9px 9px',
    backgroundImage: 'linear-gradient(180deg, #fffcf8c9, #e9e2d58a)',
    boxShadow: '0 8px 24px -12px #69583c30, inset 0 2px 0 #ffffff',
  },
  swatch: {
    position: 'relative',
    width: 96,
    height: 110,
    flexShrink: 0,
    padding: 0,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#ffffff55',
    borderRadius: '3px 3px 13px 3px',
    boxShadow: '2px 3px 5px #67502d26, 0 -3px 0 -1px #ffffff60, 0 -6px 0 -3px #c9b78450',
    cursor: { default: 'grab', ':active': 'grabbing' },
    touchAction: 'none',
    transform: {
      default: 'translateY(0)',
      ':hover': 'translateY(-5px)',
      ':focus-visible': 'translateY(-5px)',
    },
    outline: { default: 'none', ':focus-visible': '2px solid #676d54' },
    outlineOffset: 3,
  },
  swatchLine: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 10,
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: '#ffffff30',
  },
})
