import * as stylex from '@stylexjs/stylex'

export const paperStyles = stylex.create({
  yellow: {
    backgroundColor: '#fff39b',
    backgroundImage: 'linear-gradient(135deg, #fff7af, #fff18c)',
  },
  pink: {
    backgroundColor: '#f8bbd6',
    backgroundImage: 'linear-gradient(135deg, #fbd0e4, #f7b4d2)',
  },
  blue: {
    backgroundColor: '#b9e3f7',
    backgroundImage: 'linear-gradient(135deg, #c9ebfb, #addcf3)',
  },
  green: {
    backgroundColor: '#c8efbc',
    backgroundImage: 'linear-gradient(135deg, #d7f6cd, #bcebae)',
  },
  purple: {
    backgroundColor: '#dbc4f4',
    backgroundImage: 'linear-gradient(135deg, #e5d4f8, #d1b5ef)',
  },
  orange: {
    backgroundColor: '#ffd08f',
    backgroundImage: 'linear-gradient(135deg, #ffdcab, #ffc477)',
  },
})

export const styles = stylex.create({
  app: {
    backgroundColor: '#f7f4ed',
    color: '#393a32',
    fontFamily: 'Arial, Helvetica, sans-serif',
  },
  board: {
    position: 'relative',
    width: '100%',
    height: '100dvh',
    overflow: 'hidden',
    isolation: 'isolate',
    margin: 0,
    backgroundImage: 'radial-gradient(ellipse at 50% 35%, #fffdf780, transparent 75%)',
    '@media (max-width: 700px)': {
      height: 'auto',
      minHeight: '100dvh',
      padding: '18px 8px 164px',
      overflowX: 'hidden',
      overflowY: 'visible',
    },
  },
  count: {
    margin: '0 0 12px',
    textAlign: 'center',
    fontSize: 11,
    color: '#8a877b',
    letterSpacing: '0.04em',
    '@media (max-width: 700px)': {
      display: 'none',
    },
  },
  layer: (zIndex: number) => ({ zIndex }),
  note: {
    position: 'absolute',
    width: 206,
    height: 206,
    borderRadius: '2px 3px 19px 3px',
    boxShadow: '2px 9px 11px -5px #66532e30, 0 18px 24px -17px #66532e38',
    transformOrigin: '50% 25%',
  },
  position: (x: number, y: number, angle: number, zIndex: number) => ({
    left: x,
    top: y,
    transform: `rotate(${angle}deg)`,
    zIndex,
  }),
  mobileNote: {
    '@media (max-width: 700px)': {
      position: 'relative',
      left: 'auto',
      top: 'auto',
      width: 'min(88vw, 360px)',
      height: 'min(88vw, 360px)',
      margin: '0 auto 22px',
    },
  },
  mobilePosition: (x: number, y: number, angle: number) => ({
    '@media (max-width: 700px)': {
      transform: `translate3d(${x}px, ${y}px, 0) rotate(${angle}deg)`,
    },
  }),
  mobilePlaced: (x: number, y: number) => ({
    '@media (max-width: 700px)': {
      position: 'absolute',
      left: x,
      top: y,
      margin: 0,
    },
  }),
  lifted: { boxShadow: '4px 20px 28px -10px #66532e50', cursor: 'grabbing' },
  handle: {
    display: 'flex',
    width: '100%',
    height: 28,
    padding: 0,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 0,
    borderRadius: '2px 3px 0 0',
    backgroundColor: { default: '#ffffff14', ':hover': '#ffffff35' },
    cursor: { default: 'grab', ':active': 'grabbing' },
    touchAction: 'none',
    outline: { default: 'none', ':focus-visible': '2px solid #676d54' },
    outlineOffset: 3,
    '@media (max-width: 700px)': {
      height: 44,
    },
  },
  grip: {
    display: 'block',
    width: 21,
    height: 3,
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: '#71634628',
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: '#71634628',
  },
  editor: {
    display: 'block',
    width: '100%',
    height: 173,
    padding: '7px 23px 12px',
    borderWidth: 0,
    resize: 'none',
    outline: { default: 'none', ':focus-visible': '1px dashed #71634660' },
    outlineOffset: -8,
    backgroundColor: 'transparent',
    color: '#38362c',
    fontFamily: 'inherit',
    fontSize: 18,
    lineHeight: 1.65,
    letterSpacing: '0.025em',
    scrollbarWidth: 'thin',
    '@media (max-width: 700px)': {
      height: 'calc(100% - 44px)',
      padding: '10px 25px 18px',
      fontSize: 21,
    },
  },
  fold: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    width: 20,
    height: 20,
    borderRadius: '16px 0 17px 0',
    backgroundImage:
      'linear-gradient(135deg, #ffffff00 20%, #ffffff65 48%, #0000000c 52%, #ffffff40 100%)',
    boxShadow: '-2px -2px 3px #675d2710',
    pointerEvents: 'none',
  },
  preview: { pointerEvents: 'none' },
  srOnly: {
    position: 'absolute',
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: 'hidden',
    clipPath: 'inset(50%)',
    whiteSpace: 'nowrap',
    borderWidth: 0,
  },
  deleteZone: {
    position: 'fixed',
    top: 0,
    bottom: 0,
    width: 'clamp(56px, 14vw, 112px)',
    pointerEvents: 'none',
    color: '#ffffff',
  },
  deleteLeft: {
    left: 0,
    backgroundImage: 'linear-gradient(to right, #e5485de8, #f15e7070 65%, #f15e7000)',
  },
  deleteRight: {
    right: 0,
    backgroundImage: 'linear-gradient(to left, #e5485de8, #f15e7070 65%, #f15e7000)',
  },
  deleteLabel: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 8,
    paddingTop: 'max(28px, env(safe-area-inset-top))',
    fontSize: 11,
    fontWeight: 700,
    whiteSpace: 'nowrap',
    textShadow: '0 1px 4px #95263980',
  },
  dock: {
    position: 'absolute',
    bottom: 15,
    left: '50%',
    transform: 'translateX(-50%)',
    width: 694,
    '@media (max-width: 700px)': {
      position: 'fixed',
      bottom: 0,
      left: 0,
      width: '100%',
      paddingBottom: 'env(safe-area-inset-bottom)',
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      backgroundColor: '#f8f5eee8',
      boxShadow: '0 -12px 34px -18px #55472f66, inset 0 1px 0 #ffffff',
      backdropFilter: 'blur(16px)',
      transform: 'none',
    },
  },
  openDock: {
    '@media (max-width: 700px)': {
      boxShadow: '0 -18px 42px -18px #55472f78, inset 0 1px 0 #ffffff',
    },
  },
  tray: {
    display: 'flex',
    gap: 14,
    padding: '15px 21px 0',
    height: 108,
    overflow: 'hidden',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#ffffffdd',
    borderBottomColor: '#e7e0d2',
    borderRadius: '17px 17px 9px 9px',
    backgroundImage: 'linear-gradient(180deg, #fffcf8c9, #e9e2d58a)',
    boxShadow: '0 8px 24px -12px #69583c30, inset 0 2px 0 #ffffff',
    '@media (max-width: 700px)': {
      display: 'grid',
      gridTemplateColumns: 'repeat(6, minmax(0, 1fr))',
      gap: 6,
      width: '100%',
      height: 0,
      maxHeight: 0,
      padding: '0 12px',
      overflowX: 'auto',
      overflowY: 'hidden',
      borderWidth: 0,
      borderRadius: 0,
      backgroundImage: 'none',
      boxShadow: 'none',
      opacity: 0,
      transition:
        'height 180ms ease, max-height 180ms ease, padding 180ms ease, opacity 120ms ease',
      scrollbarWidth: 'none',
    },
  },
  openTray: {
    '@media (max-width: 700px)': {
      height: 126,
      maxHeight: 126,
      paddingTop: 7,
      paddingBottom: 18,
      opacity: 1,
    },
  },
  swatch: {
    position: 'relative',
    width: 96,
    height: 110,
    flexShrink: 0,
    padding: 0,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#ffffff55',
    borderRadius: '3px 3px 13px 3px',
    boxShadow: '2px 3px 5px #67502d26, 0 -3px 0 -1px #ffffff60, 0 -6px 0 -3px #c9b78450',
    cursor: { default: 'grab', ':active': 'grabbing' },
    touchAction: 'none',
    transform: {
      default: 'translateY(0)',
      ':hover': 'translateY(-5px)',
      ':focus-visible': 'translateY(-5px)',
    },
    outline: { default: 'none', ':focus-visible': '2px solid #676d54' },
    outlineOffset: 3,
    '@media (max-width: 700px)': {
      width: '100%',
      height: 94,
    },
  },
  swatchLine: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 10,
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: '#ffffff30',
  },
  sheetHandle: {
    display: 'none',
    '@media (max-width: 700px)': {
      position: 'relative',
      display: 'grid',
      gridTemplateColumns: '1fr auto auto',
      gap: 12,
      width: '100%',
      minHeight: 64,
      padding: '23px 22px 12px',
      alignItems: 'center',
      borderWidth: 0,
      borderRadius: '24px 24px 0 0',
      backgroundColor: 'transparent',
      color: '#45443b',
      fontFamily: 'inherit',
      fontSize: 15,
      fontWeight: 700,
      textAlign: 'left',
      cursor: 'pointer',
      touchAction: 'none',
      outline: { default: 'none', ':focus-visible': '2px solid #676d54' },
      outlineOffset: -5,
    },
  },
  sheetGrip: {
    '@media (max-width: 700px)': {
      position: 'absolute',
      top: 8,
      left: '50%',
      width: 38,
      height: 4,
      borderRadius: 999,
      backgroundColor: '#b7b2a6',
      transform: 'translateX(-50%)',
    },
  },
  sheetCount: {
    color: '#8a877b',
    fontSize: 12,
    fontWeight: 400,
  },
  chevron: {
    width: 9,
    height: 9,
    borderTopWidth: 2,
    borderTopStyle: 'solid',
    borderTopColor: '#6d6b61',
    borderLeftWidth: 2,
    borderLeftStyle: 'solid',
    borderLeftColor: '#6d6b61',
    transform: 'rotate(45deg)',
    transition: 'transform 180ms ease',
  },
  openChevron: {
    transform: 'rotate(225deg)',
  },
})
