import * as stylex from '@stylexjs/stylex'

export const loginStyles = stylex.create({
  page: {
    position: 'relative',
    display: 'grid',
    minHeight: '100dvh',
    padding: 'clamp(20px, 5vw, 64px)',
    placeItems: 'center',
    overflow: 'hidden',
    backgroundColor: '#f8f5ed',
    backgroundImage:
      'radial-gradient(circle at 15% 10%, #fff4bc99 0, transparent 29%), radial-gradient(circle at 84% 88%, #dfedd89c 0, transparent 31%)',
    color: '#393a32',
    fontFamily: 'Inter, "Hiragino Sans", "Yu Gothic", YuGothic, "Noto Sans JP", sans-serif',
  },
  ambientLight: {
    position: 'absolute',
    width: 'min(760px, 82vw)',
    aspectRatio: '1.25',
    borderRadius: '50%',
    backgroundColor: '#fffdf8a6',
    filter: 'blur(40px)',
    pointerEvents: 'none',
  },
  card: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    width: 'min(100%, 486px)',
    minHeight: 610,
    padding: '58px 52px 45px',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#e6dcc7',
    borderRadius: 34,
    backgroundColor: '#fffefb',
    boxShadow: '0 28px 70px -34px #66532e4d, 0 6px 20px -14px #66532e26',
    '@media (max-width: 540px)': {
      minHeight: 'min(610px, calc(100dvh - 40px))',
      padding: '42px 28px 34px',
      borderRadius: 28,
    },
    '@media (max-height: 680px)': {
      minHeight: 'calc(100dvh - 40px)',
      paddingTop: 32,
      paddingBottom: 28,
    },
  },
  wordmark: {
    alignSelf: 'center',
    color: '#393a32',
    fontFamily: 'Georgia, "Times New Roman", serif',
    fontSize: 31,
    fontWeight: 700,
    letterSpacing: '-0.035em',
    lineHeight: 1,
  },
  copy: {
    margin: '42px 0 38px',
    '@media (max-width: 540px)': { marginTop: 34, marginBottom: 30 },
    '@media (max-height: 680px)': { marginTop: 24, marginBottom: 22 },
  },
  eyebrow: {
    margin: '0 0 12px',
    color: '#d17d35',
    fontSize: 12,
    fontWeight: 800,
    letterSpacing: '0.28em',
  },
  heading: {
    margin: 0,
    color: '#292b25',
    fontSize: 'clamp(32px, 7vw, 39px)',
    fontWeight: 750,
    letterSpacing: '-0.055em',
    lineHeight: 1.35,
  },
  description: {
    margin: '22px 0 0',
    color: '#767468',
    fontSize: 15,
    letterSpacing: '0.015em',
    lineHeight: 1.85,
  },
  actions: {
    display: 'flex',
    flexDirection: 'column',
    gap: 17,
  },
  googleButton: {
    display: 'grid',
    gridTemplateColumns: '24px 1fr 24px',
    width: '100%',
    minHeight: 64,
    padding: '0 22px',
    alignItems: 'center',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: { default: '#ddd5c5', ':hover': '#c8bba4' },
    borderRadius: 14,
    backgroundColor: { default: '#ffffff', ':hover': '#fffdfa', ':active': '#f8f5ed' },
    boxShadow: {
      default: '0 5px 14px -10px #47391f70',
      ':hover': '0 8px 18px -10px #47391f70',
      ':active': '0 3px 8px -7px #47391f66',
    },
    color: '#393a32',
    fontFamily: 'inherit',
    fontSize: 16,
    fontWeight: 600,
    cursor: 'pointer',
    transform: {
      default: 'translateY(0)',
      ':hover': 'translateY(-1px)',
      ':active': 'translateY(0)',
    },
    transition:
      'border-color 160ms ease, background-color 160ms ease, box-shadow 160ms ease, transform 160ms ease',
    outline: { default: 'none', ':focus-visible': '3px solid #ead39a' },
    outlineOffset: 3,
  },
  googleMark: {
    width: 22,
    height: 22,
  },
  note: {
    margin: 0,
    color: '#8a877b',
    fontSize: 12,
    letterSpacing: '0.01em',
    lineHeight: 1.6,
    textAlign: 'center',
  },
})
